$:.unshift(File.dirname(__FILE__))  # => ["/Users/xiaohui/Ruby/yoyo/lib", "/Users/xiaohui/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/seeing_is_believing-3.2.0/lib", "/Users/xiaohui/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/seeing_is_believing-3.2.0/lib", "/usr/local/Cellar/rbenv/1.1.0/rbenv.d/exec/gem-rehash", "/Users/xiaohui/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib", "/Users/xiaohui/.rbenv/versions/2.4.1/lib/ruby/site_ruby/2.4.0", "/Users/xiaohui/.rbenv/versions/2.4.1/lib/ruby/site_ruby/2.4.0/x86_64-darwin16", "/Users/xiaohui/.rbenv/versions/2.4.1/lib/ruby/site_ruby", "/Users/xiaohui/.rbenv/versions/2.4.1/lib/ruby/vendor_ruby/2.4.0", "/Users/xiaohui/.rbenv/versions/2.4.1/lib/ruby/vendor_ruby/2.4.0/x86_64-darwin16", "/Users/xiaohui/.rbenv/versions/2.4.1/lib/ruby/vendor_ruby", "/Users/xiaohui/.rbenv/versions/2.4.1/lib/ruby/2.4.0", "/Users/xiaohui/.rbenv/versions/2.4.1/lib/ruby/2.4.0/x86_64-darwin16"]

require "yoyo"           # => true
require "active_record"  # => true

conn = { adapter: "sqlite3", database: ":memory:"  }  # => {:adapter=>"sqlite3", :database=>":memory:"}
ActiveRecord::Base.establish_connection(conn)         # => #<ActiveRecord::ConnectionAdapters::ConnectionPool:0x007fae14a521d8 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x007fae14a520c0>, @query_cache_enabled=#<Concurrent::Map:0x007fae14a52098 entries=0 default_proc=#<Proc:0x007fae14a52048@/Users/xiaohui/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/query_cache.rb:27>>, @spec=#<ActiveRecord::ConnectionAdapters::ConnectionSpecification:0x007fae14a52610 @name="primary", @config={:adapter=>"sqlite3", :database=>":memory:"}, @adapter_method="sqlite3_connection">, @checkout_timeout=5, @reaper=#<ActiveRecord::ConnectionAdapters::ConnectionPool::Reaper:0x007fae14a51fd0 @pool=#<ActiveRecord::ConnectionAdapters::ConnectionPool:0x007fae14a521d8 ...>, @frequency=nil>, @size=5, @thread_cached_conns=#<Concurrent::Map:0x007fae14a51f80 entries=0 default_proc=nil>, @connections=[], @automatic_reconnect=true, @now_conn...

class Article < ::ActiveRecord::Base                     # => ActiveRecord::Base
  connection.create_table :articles, force: true do |t|  # => #<ActiveRecord::ConnectionAdapters::SQLite3Adapter:0x007fae149d85b8 @transaction_manager=#<ActiveRecord::ConnectionAdapters::TransactionManager:0x007fae149b0720 @stack=[], @connection=#<ActiveRecord::ConnectionAdapters::SQLite3Adapter:0x007fae149d85b8 ...>>, @query_cache={}, @query_cache_enabled=false, @connection=#<SQLite3::Database:0x007fae149d8ec8 @tracefunc=nil, @authorizer=nil, @encoding=#<Encoding:UTF-8>, @busy_handler=nil, @collations={}, @functions={}, @results_as_hash=true, @type_translation=nil, @readonly=false>, @owner=#<Thread:0x007fae1507ef70 run>, @instrumenter=#<ActiveSupport::Notifications::Instrumenter:0x007fae14a52480 @id="f0c87da304f0fc9d9896", @notifier=#<ActiveSupport::Notifications::Fanout:0x007fae151e3438 @subscribers=[#<ActiveSupport::Notifications::Fanout::Subscribers::Evented:0x007fae18077628 @pattern="sql.active_record", @delegate=#<ActiveRecord::LogSubscriber:0x007fae1806c048 @queue_key="Active...
    t.string :title                                      # => [:title]
    t.text :content                                      # => [:content]
    t.timestamps                                         # => #<ActiveRecord::ConnectionAdapters::SQLite3::TableDefinition:0x007fae149a9da8 @columns_hash={"id"=>#<struct ActiveRecord::ConnectionAdapters::ColumnDefinition name="id", type=:primary_key, options={:force=>true, :primary_key=>true, :null=>false}, sql_type=nil>, "title"=>#<struct ActiveRecord::ConnectionAdapters::ColumnDefinition name="title", type=:string, options={:primary_key=>false}, sql_type=nil>, "content"=>#<struct ActiveRecord::ConnectionAdapters::ColumnDefinition name="content", type=:text, options={:primary_key=>false}, sql_type=nil>, "created_at"=>#<struct ActiveRecord::ConnectionAdapters::ColumnDefinition name="created_at", type=:datetime, options={:null=>false, :primary_key=>false}, sql_type=nil>, "updated_at"=>#<struct ActiveRecord::ConnectionAdapters::ColumnDefinition name="updated_at", type=:datetime, options={:null=>false, :primary_key=>false}, sql_type=nil>}, @indexes=[], @foreign_keys=[], @primary_keys=n...
  end                                                    # => []
end                                                      # => []

class Comment < ::ActiveRecord::Base                     # => ActiveRecord::Base
  connection.create_table :comments, force: true do |t|  # => #<ActiveRecord::ConnectionAdapters::SQLite3Adapter:0x007fae149d85b8 @transaction_manager=#<ActiveRecord::ConnectionAdapters::TransactionManager:0x007fae149b0720 @stack=[], @connection=#<ActiveRecord::ConnectionAdapters::SQLite3Adapter:0x007fae149d85b8 ...>>, @query_cache={}, @query_cache_enabled=false, @connection=#<SQLite3::Database:0x007fae149d8ec8 @tracefunc=nil, @authorizer=nil, @encoding=#<Encoding:UTF-8>, @busy_handler=nil, @collations={}, @functions={}, @results_as_hash=true, @type_translation=nil, @readonly=false>, @owner=#<Thread:0x007fae1507ef70 run>, @instrumenter=#<ActiveSupport::Notifications::Instrumenter:0x007fae14a52480 @id="f0c87da304f0fc9d9896", @notifier=#<ActiveSupport::Notifications::Fanout:0x007fae151e3438 @subscribers=[#<ActiveSupport::Notifications::Fanout::Subscribers::Evented:0x007fae18077628 @pattern="sql.active_record", @delegate=#<ActiveRecord::LogSubscriber:0x007fae1806c048 @queue_key="Active...
    t.text :content                                      # => [:content]
    t.belongs_to :article                                # => [:article]
    t.timestamps                                         # => #<ActiveRecord::ConnectionAdapters::SQLite3::TableDefinition:0x007fae1497b8b8 @columns_hash={"id"=>#<struct ActiveRecord::ConnectionAdapters::ColumnDefinition name="id", type=:primary_key, options={:force=>true, :primary_key=>true, :null=>false}, sql_type=nil>, "content"=>#<struct ActiveRecord::ConnectionAdapters::ColumnDefinition name="content", type=:text, options={:primary_key=>false}, sql_type=nil>, "article_id"=>#<struct ActiveRecord::ConnectionAdapters::ColumnDefinition name="article_id", type=:integer, options={:primary_key=>false}, sql_type=nil>, "created_at"=>#<struct ActiveRecord::ConnectionAdapters::ColumnDefinition name="created_at", type=:datetime, options={:null=>false, :primary_key=>false}, sql_type=nil>, "updated_at"=>#<struct ActiveRecord::ConnectionAdapters::ColumnDefinition name="updated_at", type=:datetime, options={:null=>false, :primary_key=>false}, sql_type=nil>}, @indexes=[[["article_id"], {}]], @f...
  end                                                    # => []

  belongs_to :article  # => {"article"=>#<ActiveRecord::Reflection::BelongsToReflection:0x007fae14952cb0 @name=:article, @scope=nil, @options={}, @active_record=Comment(id: integer, content: text, article_id: integer, created_at: datetime, updated_at: datetime), @klass=nil, @plural_name="articles", @automatic_inverse_of=nil, @type=nil, @foreign_type="article_type", @constructable=true, @association_scope_cache={}, @scope_lock=#<Thread::Mutex:0x007fae14952af8>>}
end                    # => {"article"=>#<ActiveRecord::Reflection::BelongsToReflection:0x007fae14952cb0 @name=:article, @scope=nil, @options={}, @active_record=Comment(id: integer, content: text, article_id: integer, created_at: datetime, updated_at: datetime), @klass=nil, @plural_name="articles", @automatic_inverse_of=nil, @type=nil, @foreign_type="article_type", @constructable=true, @association_scope_cache={}, @scope_lock=#<Thread::Mutex:0x007fae14952af8>>}

class Blog < Yoyo::Context    # => Yoyo::Context
  records :article, :comment  # => :available_methods
end                           # => :available_methods

Blog.instance.create_article(title: "title", content: "content")  # => #<Article id: 1, title: "title", content: "content", created_at: "2017-10-24 00:36:22", updated_at: "2017-10-24 00:36:22">
Blog.create_article(title: "title_cp", content: "content_cp")     # => #<Article id: 2, title: "title_cp", content: "content_cp", created_at: "2017-10-24 00:36:22", updated_at: "2017-10-24 00:36:22">
